razdel_2_1_2/calculator/urls.py
from django.urls import path

from . import views


app_name = 'calculator'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_calculation/', views.ProposalCreateView.as_view(), name='create'),
    path('new_calculation/result/', views.TradeFeeCalculationView.as_view(), name='result'),
    path('history/', views.ProposalHistoryView.as_view(), name='proposal_history'),
    path('generate-file/', views.generate_and_download_file, name='generate_file'),
]

razdel_2_1_2/razdel_2_1_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('calculator.urls', namespace='calculator')),
    path('admin/', admin.site.urls),
]

razdel_2_1_2/calculator/models.py
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator
from django.db import models

from .validators import validate_inn


class RateType(models.Model):
    rate_id = models.AutoField(primary_key=True)
    rate = models.DecimalField(
        'Ставка',
        max_digits=3,
        decimal_places=2
    )


class Deflator(models.Model):
    year_id = models.IntegerField(
        'Год',
        primary_key=True
    )
    deflator = models.DecimalField(
        'Коэффициент',
        max_digits=5,
        decimal_places=3
    )

    def __str__(self):
        return str(self.year_id)


class Proposal(models.Model):
    INN = models.CharField(
        verbose_name='ИНН',
        max_length=12,
        validators=[validate_inn]
    )
    inc_per_quartal = models.PositiveIntegerField(
        verbose_name='Доход за квартал',
        default=0
    )
    ins_prem = models.PositiveIntegerField(
        verbose_name='Страховые взносы',
        default=0
    )
    trade_fee_paid = models.PositiveIntegerField(
        verbose_name='Фактически уплаченная сумма торгового сбора',
        default=0
    )
    trade_fee = models.PositiveBigIntegerField(
        verbose_name='Сумма уплаченного торгового сбора',
        default=0
    )
    tax_amount = models.PositiveIntegerField(
        verbose_name='Сумма исчисленного налога',
        default=0
    )
    year = models.ForeignKey(
        Deflator,
        verbose_name='Год',
        null=True,
        on_delete=models.SET_NULL
    )
    tax_rate = models.ForeignKey(
        RateType,
        verbose_name='Ставка по налогу',
        null=True,
        on_delete=models.SET_NULL,
        default=None,
        db_column='rate_id'
    )

razdel_2_1_2/calculator/forms.py
from django.forms import ModelForm, TextInput, ModelChoiceField

from .models import Proposal, Deflator


class ProposalForm(ModelForm):
    year = ModelChoiceField(
        queryset=Deflator.objects.all(),
        label='Год',
        empty_label=None,
        to_field_name='year_id'
    )

    class Meta:
        model = Proposal
        fields = ['INN', 'inc_per_quartal', 'ins_prem', 'trade_fee_paid', 'year']
        widgets = {
            'INN': TextInput(attrs={'type': 'number'})
        }

razdel_2_1_2/calculator/views.py
import os
from math import ceil

from django.shortcuts import render, redirect
from django.views.generic import CreateView, TemplateView, ListView
from django.urls import reverse_lazy
from django.http import HttpResponse

from .models import Proposal, RateType
from .forms import ProposalForm
from .constants import LOWER_BOUND, UPPER_BOUND


def index(request):
    template = 'calculator/index.html'
    return render(request, template)


class ProposalCreateView(CreateView):
    model = Proposal
    form_class = ProposalForm
    template_name = 'calculator/new_calculation.html'
    success_url = reverse_lazy('calculator:result')

    def form_valid(self, form):
        proposal = form.save(commit=False)

        income = form.cleaned_data['inc_per_quartal']

        selected_year = form.cleaned_data['year']
        deflator = selected_year.deflator

        limit_1 = LOWER_BOUND * deflator
        limit_2 = UPPER_BOUND * deflator

        if income < limit_1:
            proposal.tax_rate = RateType.objects.get(rate_id=1)
        elif limit_1 < income < limit_2:
            proposal.tax_rate = RateType.objects.get(rate_id=2)

        tax_amount = ceil(proposal.inc_per_quartal * proposal.tax_rate.rate)
        insurance_premium = proposal.ins_prem
        trade_fee_paid = proposal.trade_fee_paid

        trade_fee = min(tax_amount - insurance_premium, trade_fee_paid)
        
        proposal.tax_amount = tax_amount
        proposal.trade_fee = trade_fee

        proposal.save()
        return redirect(self.success_url)


class TradeFeeCalculationView(TemplateView):
    template_name = 'calculator/result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        last_proposal = Proposal.objects.latest('id')

        tax_amount = last_proposal.tax_amount
        insurance_premium = last_proposal.ins_prem
        trade_fee_paid = last_proposal.trade_fee_paid
        trade_fee = last_proposal.trade_fee

        context = {
            'tax_amount': tax_amount,
            'insurance_premium': insurance_premium,
            'trade_fee_paid': trade_fee_paid,
            'trade_fee': trade_fee
        }
        return context


class ProposalHistoryView(ListView):
    model = Proposal
    template_name = 'calculator/proposal_history.html'
    context_object_name = 'proposals'
    paginate_by = 10


def generate_and_download_file(request):
    try:
        last_proposal = Proposal.objects.latest('id')

        data = {    
            'ИНН': last_proposal.INN,
            'Доход за квартал': last_proposal.inc_per_quartal,
            'Страховые взносы': last_proposal.ins_prem,
            'Фактически уплаченная сумма торгового сбора': last_proposal.trade_fee_paid,
            'Сумма уплаченного торгового сбора': last_proposal.trade_fee,
            'Год': last_proposal.year.year_id,
            'Ставка по налогу': last_proposal.tax_rate.rate,
            'Сумма исчисленного налога': last_proposal.tax_amount,
        }
        # Определяем путь к файлу template.txt
        template_file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template.txt')

        # Открываем файл шаблона и считываем его содержимое
        with open(template_file_path, 'r') as template_file:
            template_content = template_file.read()

        # Заменяем заполнители в шаблоне на данные
        filled_content = template_content.format(**data)

        response = HttpResponse(filled_content, content_type='application/txt')

        response['Content-Disposition'] = 'attachment; filename="filled_proposal.txt"'

        return response

    except Proposal.DoesNotExist:
        return HttpResponse("Ошибка: Объект Proposal не найден")

razdel_2_1_2/templates/calculator/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <h2>Главная страница</h2>
        <a href="{% url 'calculator:create' %}" class="btn btn-primary">Сделать новый расчет</a>
        <a href="{% url 'calculator:proposal_history' %}" class="btn btn-secondary">История расчетов</a>
    </div>
</body>
</html>

razdel_2_1_2/templates/calculator/new_calculation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Форма</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container col-4 m-3" >
        <h2>Введите данные</h2>
        <form action="{% url 'calculator:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
    </div>
</body>
</html>

razdel_2_1_2/templates/calculator/proposal_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>История расчетов</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4 text-center">История расчетов</h1>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ИНН</th>
                    <th scope="col">Доход за квартал</th>
                    <th scope="col">Сумма исчисленного налога за квартал</th>
                    <th scope="col">Страховые взносы</th>
                    <th scope="col">Фактически уплаченная сумма торгового сбора</th>
                    <th scope="col">Сумма уплаченного торгового сбора</th>
                    <th scope="col">Год</th>
                    <th scope="col">Ставка по налогу</th>
                </tr>
            </thead>
            <tbody>
                {% for proposal in proposals %}
                <tr>
                    <td>{{ proposal.INN }}</td>
                    <td>{{ proposal.inc_per_quartal }}</td>
                    <td>{{ proposal.tax_amount }}</td>
                    <td>{{ proposal.ins_prem }}</td>
                    <td>{{ proposal.trade_fee_paid }}</td>
                    <td>{{ proposal.trade_fee }}</td>
                    <td>{{ proposal.year.year_id }}</td>
                    <td>{{ proposal.tax_rate.rate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Пагинация -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo; первая</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo; предыдущая</span>
                    </a>
                </li>
                {% endif %}

                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        Страница {{ page_obj.number }} из {{ paginator.num_pages }}
                    </a>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">следующая &raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">последняя &raquo;</span>
                    </a>
                </li>
                {% endif %}
                
            </ul>
            <div class="text-center mt-3">
                <a href="{% url 'calculator:index' %}" class="btn btn-primary">На главную</a>
            </div>
        </nav>
    </div>
</body>
</html>

razdel_2_1_2/templates/calculator/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Результат вычислений</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Результат расчета суммы торгового сбора, уменьшающего сумму налога</h1>
        <div class="row">
            <div class="col-md-6">
                <h4>Сумма исчисленного налога:</h4>
                <p>{{ tax_amount }}</p>
                <h4>Сумма страховых взносов:</h4>
                <p>{{ insurance_premium }}</p>
                <h4>Фактически уплаченная сумма торгового сбора:</h4>
                <p>{{ trade_fee_paid }}</p>
            </div>
            <div class="col-md-6">
                <h4>Сумма торгового сбора, уменьшающего сумму налога:</h4>
                <p>{{ trade_fee }}</p>	
            </div>
        </div>
		<a href="{% url 'calculator:index' %}" class="btn btn-primary mt-3">Вернуться на главную</a>
        <a href="{% url 'calculator:generate_file' %}" class="btn btn-success mt-3">Скачать заполненную форму</a>
    </div>
</body>
</html>